apiVersion: v1
kind: ImageStream
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: rabbitmq-slave
  name: rabbitmq-slave
spec:
  tags:
  - annotations: null
    from:
      kind: DockerImage
      name: microservices/rabbitmq
    generation: null
    importPolicy: {}
    name: latest
status:
  dockerImageRepository: ""
