version: '3'

networks: 
    poc:
        driver: bridge

services:
    rabbitmq:
        hostname: rabbitmq
        container_name: rabbitmq
        image: poc/rabbitmq
        build: 
            context: ./broker
            dockerfile: Dockerfile
        networks: 
            - poc
        ports:
            - 15672:15672
            - 5672:5672
        volumes:
            - ./data/rabbit:/var/lib/rabbitmq:rw
            - ./broker/configuration/definitions.json:/opt/definitions.json:ro
            - ./broker/configuration/rabbit.config:/etc/rabbitmq/rabbitmq.config:ro
            - ./broker/plugins/enabled_plugins:/etc/rabbitmq/enabled_plugins
